name: "Bug Report"
description: "Report a bug or problem with StreamChat+"
title: "ðŸž Bug"
labels: ["bug", "problem", "issue"]
assignees:
  - unordentlich
body:
  - type: markdown
    attributes:
      value: |
        You have found a bug and want to report it? Thanks a lot! âœ¨
  - type: input
    id: contact
    attributes:
      label: Discord
      description: Please enter your discord-tag#0000 for further inquiries
      placeholder: jonas#6789
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Please explain what the problem is and to what extent it limits you in playing.
      placeholder: The addon crashes permanently after changing a setting and cannot be started afterwards.
    validations:
      required: true
  - type: textarea
    id: how-reproduce
    attributes:
      label: How to reproduce the bug?
      description: Please explain how to invoke the bug again for possible experimentation with the issue.
      placeholder: Start your game. Open the settings and change the "Twitch Token" field. Now the game crashes. Now start it again. It will now crash from exiting the Minecraft Launcher loading bar.
    validations:
      required: true
  - type: input
    id: labymod-log
    attributes:
      label: LabyMod-Debug Log
      description: Please provide a link to the LabyMod debug log. You can open it by pressing in the lower left corner of your Start menu. You can upload it to https://paste.labymod.net/.
    validations:
      required: false
  - type: input
    id: addon-log
    attributes:
      label: Addon-Debug Log
      description: Please provide a link to the addon debug log. You can open it by double-clicking the > Support < button in the addon settings. You can upload it to https://paste.labymod.net/.
    validations:
      required: false
  - type: textarea
    id: other
    attributes:
      label: Anything else?
      description: I read through everything! Whether stories about dinosaurs, more information about the bug or feedback about the addon! ðŸ¦–
      placeholder: Once upon a time there was a little green dinosaur. His name was Rex and he went on a journey with his friends. On the trip he met a female dinosaur named Rexina. They became best friends and always shared their food. At some point Rexina was hit by a tree during a heavy thunderstorm and Rex lost the love of his life. The End. :(
|
*Joking, of course they have been in love and married until the end of their lives lmao
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Up to date?
      description: Please check if the addon is on the latest version.
      options:
        - label: I have installed the latest stable version of the addon.
          required: true
